### ISSUE TITLE
"Carriage return character missing." error occurs on first line in Sublime Text. (Windows, Ruby 2.3.3)

### ISSUE THREAD

**Issue by johnsirett** [SublimeLinter/SublimeLinter-rubocop#37]
Like the title says, the "Carriage return character missing." warning appears on the first line in ruby files with "rubocop" linter enabled.

Fails on a program as simple as:
`puts 'Hello world!'`

Using default rubocop end-of-line behaviour (:native -> expects CRLF on windows) Running rubocop from the command line (Git Bash) claims no offenses.

Using Windows 10, with Ruby 2.3.3 (from RailsInstaller).

**Comment by johnsirett** [comment]
This is on ANY first line BTW. Same issue does not occur in subsequent lines in the file.

**Comment by schmitmd** [comment]
https://github.com/bbatsov/rubocop/issues/4293

**Comment by ljkbennett** [comment]
Not related to the linter - @schmitmd's link seems to explain how to fix it, so closing.
