### ISSUE TITLE
Wrong ruby executable taken, when using with rvm.

### ISSUE THREAD

**Issue by RaimundHuebel** [SublimeLinter/SublimeLinter-rubocop#41]
##### General Infos

- Operating System: Linux (Debian jessie)
- Sublime Text version: Build 3126
- Details about your config e.g. do you use rbenv, rvm or your_own_command to run rubocop?:
Using rvm, includin rvm-auto-ruby
 
##### Problem & Fix:

When using SublimeLinter-rubocop the Linter always use 'ruby' to execute rubocop, whereas SublimeLinter-RubyLinter has detected `rvm-auto-ruby` as executable.

    # The problematic line is (in linter.rb):
    class RuboCop(RubyLinter):
        ...
        def cmd(self):
            ...
            #NOW: Here is ruby is hardcoded.
            command = ['ruby', '-S', 'rubocop', '--format', 'emacs']
            #BETTER:
            command = self.executable_path + ['-S', 'rubocop', '--format', 'emacs']

With kind regards, Raimund

**Comment by ljkbennett** [comment]
Hi @RaimundHuebel thanks for your contribution. I've just gotten involved with maintenance of this project and I need to take a deeper look so I can understand the possible issues this might cause, particularly in relation to https://github.com/SublimeLinter/SublimeLinter-rubocop/issues/26

I am on it and will get back to you asap. Thanks again.

**Comment by mvastola** [comment]
Is there any movement on this? Having this exact issue.

**Comment by ljkbennett** [comment]
Yes, I am just working on another PR for editing the command to be run and then there will be a new release with this in.

**Comment by mvastola** [comment]
Thanks!

**Comment by arielkirkwood** [comment]
@ljkbennett Need any help? Looking to set this up with a bundled copy of Rubocop instead of just the system default.

**Comment by ckhall** [comment]
please see https://github.com/SublimeLinter/SublimeLinter-rubocop/pull/47

**Comment by douglas** [comment]
Perhaps [this](https://github.com/SublimeLinter/SublimeLinter3/pull/670) helps as well.

**Comment by braver** [comment]
closed via #47
