### ISSUE TITLE
Chef rubocop cookstyle (RE: #36)

### ISSUE THREAD

**Issue by mengesb** [SublimeLinter/SublimeLinter-rubocop#43]
This is related to #36 

To run Chef's cookstyle profile, on mac I execute the following:

`chef exec rubocop -S -r cookstyle`

While I know there's settings for the plugin for arguments, there's no clear definition here as to which executable to run rubocop will be used. Unless i'm misinterpreting configuration, I'd love to be able to specify exactly what the command to perform the linting will be.

**Comment by ljkbennett** [comment]
Ok, I think we can do this via a new option, but I won't be able to test it as I am not using chef. If I send you a PR when it's up can you take a look for me? Will be next week now.

**Comment by mengesb** [comment]
Yeah I can do that

**Comment by kaste** [comment]
There is a new minimal implementation of this plugin at https://github.com/SublimeLinter/SublimeLinter-rubocop/pull/55

Using this you could set `executable` to `['chef', 'exec', 'rubocop']`. Note that other args like `--format emacs` are (currently) still static. However, you could set `"args": ["-r", "cookstyle"]` to *add* arguments to the `cmd`.

**Comment by kaste** [comment]
Closing due to age and lack of interaction. To set `executable` as in my previous comment is still an option.
