### ISSUE TITLE
PackageControl cannot find this package

### ISSUE THREAD

**Issue by Hansenq** [SublimeLinter/SublimeLinter-rubocop#48]
I'm unable to download this package from PackageControl. Going to the page for this plugin at https://packagecontrol.io/packages/SublimeLinter-rubocop, there's a sign saying that this package is missing, with the following message:
```
Package info was unavailable last time crawler ran. Error downloading repository. HTTP exception 
InvalidCertificateException (Host api.github.com returned an invalid certificate ([SSL: 
TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading 
https://api.github.com/repos/SublimeLinter/SublimeLinter-rubocop.
```

**Comment by kaste** [comment]
A lot of packages have this flag currently. This is an issue on Package Control.

You could manually clone this repo into your packages folder, if you want/need this now. Otherwise, you would have to wait until Package Control resolves the links again.
