### ISSUE TITLE
Not working with SublimeLinter 4

### ISSUE THREAD

**Issue by meetajhu** [SublimeLinter/SublimeLinter-rubocop#49]
This Linter was working flawlessly with SublimeLinter3 until the recent forced update to SublimeLinter 4. No linting or no error in console.
From Console: 
``` reloading plugin SublimeLinter-rubocop.linter ```

Then nothing happens. Rubocop works in CL.

**Comment by kaste** [comment]
That's not enough info to debug an issue, honestly. Enable debug mode, restart Sublime and post the console log.

If it really does absolutely nothing (no warnings) then it typically means that it doesn't recognize the syntax of your view/buffer.

**Comment by meetajhu** [comment]
Is there any other better way to debug other than console errors?

**Comment by kaste** [comment]
I don't understand. You probably don't want to debug python code here and now.

**Comment by foton** [comment]
Startup Sublime 3 in debug mode: 
    
    DPI scale: 1
    startup, version: 3143 linux x64 channel: stable
    executable: /opt/sublime_text/sublime_text
    working dir: /
    packages path: /home/foton/.config/sublime-text-3/Packages
    state path: /home/foton/.config/sublime-text-3/Local
    zip path: /opt/sublime_text/Packages
    zip path: /home/foton/.config/sublime-text-3/Installed Packages
    ignored_packages: ["GitGutter", "Vintage"]
    ignoring deprecated syntax definition: Packages/Ruby on Rails snippets/HTML (Rails).tmLanguage
    pre session restore time: 0.159505
    startup time: 0.375407
    first paint time: 0.390357
    reloading plugin Default.auto_indent_tag
    reloading plugin Default.block
    reloading plugin Default.comment
    reloading plugin Default.convert_syntax
    reloading plugin Default.copy_path
    reloading plugin Default.delete_word
    reloading plugin Default.detect_indentation
    reloading plugin Default.duplicate_line
    reloading plugin Default.echo
    reloading plugin Default.exec
    reloading plugin Default.fold
    reloading plugin Default.font
    reloading plugin Default.goto_line
    reloading plugin Default.history_list
    reloading plugin Default.indentation
    reloading plugin Default.install_package_control
    reloading plugin Default.kill_ring
    reloading plugin Default.mark
    reloading plugin Default.new_templates
    reloading plugin Default.open_context_url
    reloading plugin Default.open_in_browser
    reloading plugin Default.pane
    reloading plugin Default.paragraph
    reloading plugin Default.paste_from_history
    reloading plugin Default.profile
    reloading plugin Default.quick_panel
    reloading plugin Default.run_syntax_tests
    reloading plugin Default.save_on_focus_lost
    reloading plugin Default.scroll
    reloading plugin Default.set_unsaved_view_name
    reloading plugin Default.settings
    reloading plugin Default.show_scope_name
    reloading plugin Default.side_bar
    reloading plugin Default.sort
    reloading plugin Default.swap_line
    reloading plugin Default.switch_file
    reloading plugin Default.symbol
    reloading plugin Default.transform
    reloading plugin Default.transpose
    reloading plugin Default.trim_trailing_white_space
    reloading plugin Default.ui
    reloading plugin CSS.css_completions
    reloading plugin Diff.diff
    reloading plugin HTML.encode_html_entities
    reloading plugin HTML.html_completions
    reloading plugin 0_package_control_loader.00-package_control
    reloading plugin 0_package_control_loader.01-pygments
    reloading plugin 0_package_control_loader.50-markupsafe
    reloading plugin 0_package_control_loader.50-pymdownx
    reloading plugin 0_package_control_loader.50-python-markdown
    reloading plugin 0_package_control_loader.50-pyyaml
    reloading plugin 0_package_control_loader.51-python-jinja2
    reloading plugin 0_package_control_loader.55-jsonschema
    reloading plugin 0_package_control_loader.55-mdpopups
    reloading plugin AdvancedNewFile.AdvancedNewFile
    reloading plugin All Autocomplete.all_views_completions
    reloading plugin Better CoffeeScript.CoffeeScript
    reloading plugin Cucumber.GherkinAutoComplete
    reloading plugin Cucumber.table_cleaner
    reloading plugin Cucumber.table_commons
    reloading plugin Cucumber.table_import
    reloading plugin Gherkin (Cucumber) Formatter.__init__
    reloading plugin Gherkin (Cucumber) Formatter.sublime-gherkin-formatter
    reloading plugin Git.git_commands
    reloading plugin GitHub Flavored Markdown Preview.GHMarkdownPreview
    reloading plugin Goto Usage.GotoUsage
    reloading plugin Goto Usage.__init__
    reloading plugin Goto Usage.core
    reloading plugin Goto Usage.dep_graph
    reloading plugin Goto Usage.utils
    reloading plugin Package Control.1_reloader
    reloading plugin Package Control.2_bootstrap
    reloading plugin Package Control.Package Control
    reloading plugin SublimeLinter-contrib-reek.linter
    reloading plugin SublimeLinter-rubocop.linter
    reloading plugin SublimeLinter.__init__
    reloading plugin SublimeLinter.busy_indicator_view
    reloading plugin SublimeLinter.commands
    reloading plugin SublimeLinter.goto_commands
    reloading plugin SublimeLinter.highlight_view
    reloading plugin SublimeLinter.log_handler
    reloading plugin SublimeLinter.message_view
    reloading plugin SublimeLinter.panel_view
    reloading plugin SublimeLinter.status_bar_view
    reloading plugin SublimeLinter.sublime_linter
    reloading plugin SublimeLinter.tooltips_view
    reloading plugin Babel.Babel
    plugins loaded
    Package Control: No updated packages
    Indexing gherkin phrases done

No errors marked in `pictogram.rb`:

    module Catalog
      class Pictogram < ApplicationRecord
        include TrackActivity
        include ActivityTrails

        CODE_REGEXP_STR = '[a-z\-]+'
        self.table_name = 'catalog_pictograms'

        validates :slug,
                  presence: true,
                  uniqueness: true,
                  format: { with: /\A[a-z\-]+\z/, message: I18n.t('catalog.pictogram.errors.slug_have_bad_format') }
        validates :title, presence: true
        validates :view_box, presence: true
        validates :svg_body, presence: true


        scope :by_code, ->(code) { where('codes_csv LIKE ?', "%,#{code.delete(':').strip},%") }

        track_activity

        def full_code
          slug
        end
      end
    end

When I run rubocop from shell, 2 offenses are found:

    foton@NTB-Mlcosi:~$ rubocop Dokumenty/workspace/queens_fresh/app/models/catalog/pictogram.rb 
    Inspecting 1 file
    /home/foton/Dokumenty/workspace/queens_fresh/.rubocop.yml: Naming/PredicateName has the wrong namespace - should be Style
    /home/foton/Dokumenty/workspace/queens_fresh/.rubocop.yml: Naming/FileName has the wrong namespace - should be Style
    Warning: unrecognized cop Rails/HasManyOrHasOneDependent found in /home/foton/Dokumenty/workspace/queens_fresh/.rubocop.yml
    Warning: unrecognized cop Rails/CreateTableWithTimestamps found in /home/foton/Dokumenty/workspace/queens_fresh/.rubocop.yml
    Warning: unrecognized cop Rails/InverseOf found in /home/foton/Dokumenty/workspace/queens_fresh/.rubocop.yml
    Warning: unrecognized cop Style/MixinUsage found in /home/foton/Dokumenty/workspace/queens_fresh/.rubocop.yml
    C

    Offenses:

    Dokumenty/workspace/queens_fresh/app/models/catalog/pictogram.rb:25:23: C: Freeze mutable objects assigned to constants.
        CODE_REGEXP_STR = '[a-z\-]+'
                          ^^^^^^^^^^
    Dokumenty/workspace/queens_fresh/app/models/catalog/pictogram.rb:36:1: C: Extra blank line detected.

    1 file inspected, 2 offenses detected

**Comment by foton** [comment]
From now it seems taht setting ``"debug": true`` in ``Packages/User/Preferences.sublime-settings`` does not change console log :-(

**Comment by kaste** [comment]
The setting is in the SublimeLinter settings not in your main user settings.

**Comment by kaste** [comment]
Nana, in the menu Preferences > Package Settings > SublimeLinter.

Something like that.

**Comment by dikond** [comment]
Hi! I also noticed it isn't working with sublime-linter 4. The error I see constantly in the console is

```
startup, version: 3143 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/danny/Library/Application Support/Sublime Text 3/Packages
state path: /Users/danny/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/danny/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
Errors parsing theme:
icon_folder_loading is missing layer0.opacity, setting to 1.0 for backwards compatibility
icon_file_type is missing layer0.opacity, setting to 1.0 for backwards compatibility
pre session restore time: 0.636371
using gpu buffer for window
startup time: 0.715107
reloading plugin Default.auto_indent_tag
...
...reloading a bunch of plugins...
...
reloading plugin ESLint.ESLint
plugins loaded
environment variables loaded using: /bin/bash -l
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 435, in on_load_async
    callback.on_load_async(v)
  File "rubocop_listener in /Users/danny/Library/Application Support/Sublime Text 3/Installed Packages/RuboCop.sublime-package", line 141, in on_load_async
  File "rubocop_listener in /Users/danny/Library/Application Support/Sublime Text 3/Installed Packages/RuboCop.sublime-package", line 128, in do_in_file_check
  File "rubocop_listener in /Users/danny/Library/Application Support/Sublime Text 3/Installed Packages/RuboCop.sublime-package", line 121, in mark_issues
  File "rubocop_listener in /Users/danny/Library/Application Support/Sublime Text 3/Installed Packages/RuboCop.sublime-package", line 114, in run_rubocop
  File "rubocop_runner in /Users/danny/Library/Application Support/Sublime Text 3/Installed Packages/RuboCop.sublime-package", line 50, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/Users/danny/.rvm/bin/rvm-auto-ruby'
```

**Comment by kaste** [comment]
@dikond Here throws a completely different package.

**Comment by dikond** [comment]
@kaste I see, sorry for bothering 😓 
Removed all rubocop-related plugins and re-installed SublimeLinter-rubocop. I have 0 errors now, but sublime linter doesn't show violations for some reason now. Although rubocop (gem) does show. But I think it isn't related to this package.

**Comment by kaste** [comment]
We should figure what command exactly you're running on the cli. 

> SublimeLinter: #1 SublimeLinter.sublime-package:1184: rubocop: application.rb 

> ['/Users/danny/.rbenv/shims/ruby', '-S', 'rubocop', '--format', 'emacs', '--force-exclusion', '--stdin', '/Users/danny/dev/elixirator/enbro_crm/apps/api_v1/application.rb']

That's really basically the command we're running here (shlexed). More or less you can join here by `' '`

> SublimeLinter: #1 SublimeLinter.sublime-package:1187: rubocop: cwd: /Users/danny/dev/elixirator/enbro_crm

That's the working dir.

**Comment by kaste** [comment]
Does it need special environment variables. 

I mean it doesn't show any output in your gist

a) It's still working on the problem LOL
b) There is zero output, nada

Otherwise it would at least crash

**Comment by dikond** [comment]
So I tried different variations of commands here are my results

1) Without `--stdin`
> /Users/danny/.rbenv/shims/ruby -S rubocop --format emacs --force-exclusion /Users/danny/dev/elixirator/enbro_crm/apps/api_v1/application.rb
Result: process either idle or hangs? No output and no prompt in terminal :)

2) Without `--force-exclusion` & `--stdin`
> /Users/danny () ツ /Users/danny/.rbenv/shims/ruby -S rubocop --format emacs /Users/danny/dev/elixirator/enbro_crm/apps/api_v1/application.rb
/Users/danny/dev/elixirator/enbro_crm/apps/api_v1/application.rb:7:18: W: Lint/UnneededDisable: Unnecessary disabling of `Metrics/BlockLength`.
/Users/danny/dev/elixirator/enbro_crm/apps/api_v1/application.rb:263:29: W: Lint/UnneededDisable: Unnecessary disabling of `Metrics/BlockLength`.

Result: it works!

3) Without `--force-exclusion`
> /Users/danny/.rbenv/shims/ruby -S rubocop --format emacs --force-exclusion /Users/danny/dev/elixirator/enbro_crm/apps/api_v1/application.rb

Result: no output
---
Gonna check my exclusion rules...

**Comment by dikond** [comment]
Well, I can confirm that SublimeLinter-rubocop is working... [here is the gist with a proof](https://gist.github.com/dikond/0fcf8db11aece4207f074bd26e9eed73). It just doesn't lint in some projects, which makes me think it's 99% related to exclusion rules somehow 😅

**Comment by kaste** [comment]
☺️ 

Honestly, I don't know what `--force-exclusion ` does. It was there and it is on by default. 😬

**Comment by foton** [comment]
I fix my issue too, adding `"debug": true` to `Preferences > Package Settings > SublimeLinter > Settings :User` reveal, that path ` "~/.rbenv/shims"` is not in paths for Sublime Linter. After adding it (http://sublimelinter.readthedocs.io/en/latest/troubleshooting.html#adding-to-the-paths-setting). Linter works.
But results are displayed little differently, so my guess is that previous settings was erased during update of Sublime Linter.

**Comment by kaste** [comment]
You mean the colors are different? 

I've found a comment here https://github.com/SublimeLinter/SublimeLinter/issues/1074#issuecomment-370265068 how to customize the colors.

**Comment by kaste** [comment]
Don't know. The OP never showed up again, two highjackers are (hopefully) happy, so I'm closing. 💪
