### ISSUE TITLE
Defining 'cls.syntax' has been deprecated

### ISSUE THREAD

**Issue by 1dustindavis** [SublimeLinter/SublimeLinter-rubocop#58]
When loading SublimeLinter-rubocop.linter, this error can be seen in Sublime's console:
`reloading plugin SublimeLinter-rubocop.linter`
`rubocop: Defining 'cls.syntax' has been deprecated. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector`

Same issue was experienced by another SublimeLinter plugin: https://github.com/maristgeek/SublimeLinter-contrib-bashate/issues/17

And was resolved like this:
https://github.com/maristgeek/SublimeLinter-contrib-bashate/commit/05002193236abedb2ed7afd92ca7b86f50886ffc

**Comment by kaste** [comment]
Thanks again for the PR.

**Comment by wnesbv69** [comment]
все html 'cls.syntax' не работают
