### ISSUE TITLE
Not working in Sublime

### ISSUE THREAD

**Issue by AlbertMontolio** [SublimeLinter/SublimeLinter-rubocop#62]
I have followed your instructions:

Adding
      "args": ["--config", "path/to/config.yml"],

to the settings of Sublime Linter

But I get 
<img width="671" alt="screen shot 2018-08-13 at 09 48 08" src="https://user-images.githubusercontent.com/2828986/44019074-0987e126-9ede-11e8-8f37-d7ebe34fdc00.png">

Rubocop(erred).

Any ideas what might be wrong?

**Comment by kaste** [comment]
Hi!

Please enable debug mode in your user settings. Open View > Console and look at the output.

**Comment by AlbertMontolio** [comment]
In the debug mode I get:

```
ApplySyntax: Syntax set to Ruby on Rails using Packages/Rails/Ruby on Rails.sublime-syntax
SublimeLinter: WARNING: rubocop output:
/usr/bin/ruby: no Ruby script found in input (LoadError)
````

I checked this thread in github:

https://github.com/asdf-vm/asdf/issues/64

They do a hack with the path, but I am kind of new and I don't really grasp what they do.

Here is my path

```
export PATH="./bin:./node_modules/.bin:${PATH}:/usr/local/sbin"
````

**Comment by kaste** [comment]
Hm, you're not in debug mode yet which will be relatively verbose. Please open and edit `Preferences: SublimeLinter Settings` (best to use Sublime's command palette ctrl+shift+p)

It looks like it uses the standard `/usr/bin/ruby` though. You may have to look at setting  `executable` to `/path/to/my/real/ruby`. 

A bit related if you use rvm -> https://github.com/SublimeLinter/SublimeLinter/issues/1479

**Comment by braver** [comment]
Closed due to inactivity
