### ISSUE TITLE
--stdin requires exactly one path

### ISSUE THREAD

**Issue by giann** [SublimeLinter/SublimeLinter-rubocop#64]
I get the following error (note that I don't have a .rubocop.yml):

`-s/--stdin requires exactly one path, relative to the root of the project. RuboCop will use this path to determine which cops are enabled (via eg. Include/Exclude), and so that certain cops like Naming/FileName can be checked.`

**Comment by kaste** [comment]
Hi @giann!  You could give PR #55 a try!

**Comment by kaste** [comment]
Closing due to lack of interaction. A new version of this plugin has shipped right now anyway.

Please reopen if you want to.

**Comment by nrogap** [comment]
I think this one occurs when your file name and class name don't equal.
Example
app/models/design.rb
`Class DesignAja < ApplicationRecord`
`end`
As you see, `DesignAja` is not equal `design.rb`
