### ISSUE TITLE
Tooltip on hover is always too small with certain font sizes

### ISSUE THREAD

**Issue by jtrees** [SublimeLinter/SublimeLinter-rubocop#68]
#### Description.
The tooltip box with information about a given rubocop error is always too small for me. I noticed this only occurs with the font size set to 11 or higher.

#### System Info
* OS: elementary OS Juno (5.0) [based on Ubuntu 18.04]
* Sublime Text 3.2.1 (build 3207)
* SublimeLinter v4.11.3
* SublimeLinter-rubocop v3.0.0

Relevant Sublime Text settings:
```json
{
    "font_face": "",
    "font_size": 11
}
```

I believe the font face I'm using (which is simply the default) is "Roboto Mono".

#### Screenshot
![Screenshot from 2019-07-18 11 29 55](https://user-images.githubusercontent.com/5802758/61446650-c8ed0d80-a94f-11e9-942d-386cc5887615.png)

**Comment by kaste** [comment]
Thanks for reporting. This has been fixed in SublimeLinter core and is ready to release.

**Comment by kaste** [comment]
Shipped with https://github.com/SublimeLinter/SublimeLinter/releases/tag/4.12.0
