### ISSUE TITLE
ruby: invalid option --format

### ISSUE THREAD

**Issue by maprihoda** [SublimeLinter/SublimeLinter-rubocop#70]
With the debug option set to true, the console output shows:

```
SublimeLinter: #3 linter.py:786       WARNING: rubocop output:
ruby: invalid option --format  (-h will show valid options) (RuntimeError)

```

and the linter doesn't work, obviously.

ruby 2.7.0p0
latest SublimeLinter

**Comment by kaste** [comment]
If you already have "debug" on, what's the command SublimeLinter is running here? Does it look sane?

**Comment by maprihoda** [comment]
```
  /home/user/code/ruby/test-app  (working dir)
  $ cat app/models/user.rb | /home/user/.rbenv/shims/ruby --format emacs --force-exclusion --stdin /home/user/code/ruby/test-app/app/models/user.rb

SublimeLinter: #2 linter.py:786       WARNING: rubocop output:
ruby: invalid option --format  (-h will show valid options) (RuntimeError)
```

**Comment by kaste** [comment]
I don't see how you'd get that command without changing the settings? Are you sure on the latest version of this plugin?

Is there anything else in the debug output of interest?

**Comment by maprihoda** [comment]
resolved, [see](https://github.com/SublimeLinter/SublimeLinter-ruby/issues/23#issuecomment-598388512)

Thanks for you help.

**Comment by kaste** [comment]
💐
