### ISSUE TITLE
Cannot use `executable` with `use_bundle_exec`?

### ISSUE THREAD

**Issue by joshuapinter** [SublimeLinter/SublimeLinter-rubocop#74]
I'm using `rbenv` and I'm trying to use the `rubocop` that we have in our `bundle`. 

I have my `executable` set to `~/me/.rbenv/shims/rubocop` and `use_bundle_exec` to `true`.

Based on the console log it's not finding the right executable. 

If I look at [the code](https://github.com/SublimeLinter/SublimeLinter-rubocop/blob/9bf25c766db9f61a7f554818c5d63430e4697f8f/linter.py#L11), it appears that if `executable` is set, it ignores `use_bundle_exec`. Am I wrong?

For reference, if I run `bundle exec rubocop` in my project directory, everything works great. Running just `rubocop` it does not. 

FYI, I'm a contributor to `rubocop` so we use various `github` branches in our `Gemfile` to pull and test the master branch of the gem.

Thanks!

**Comment by kaste** [comment]
You're correct, setting executable disables all other settings.  Two things can go wrong, at least.  1. Maybe we don't set the correct working dir.  We Print that in debug mode.  2. The process environment of Sublime itself is different from your Terminal.  You could check that by closing Sublime completely, and starting it again using subl . from the Terminal.  It should then inherit the ENV from the Terminal.

**Comment by joshmfrankel** [comment]
@joshuapinter Have you tried overriding the `env` for the rubocop linter in your settings file? For example here is mine with asdf. I'm guessing rbenv is similiar in that you can use `~/.rbenv/shims` as the environment override

```
"rubocop": {
      "use_bundle_exec": true,
      "env": {
        "PATH": "~/.asdf/shims:$PATH"
      }
    }
```

**Comment by joshuapinter** [comment]
@joshmfrankel Hey Josh. Not sure why I didn't reply to this originally but just wanted to follow-up and say that the configuration change you suggested worked perfectly. It now finds and uses the `rubocop` binary in my `~/.rbenv/shims` directory. My final config looks like this: 

```json
{
  "linters": {
    "rubocop": {
      "use_bundle_exec": true,
      "env": {
        "PATH": "~/.rbenv/shims:$PATH"
      }
    }
  }
}
```

Belated thank you! 🙏

**Comment by williantenfen** [comment]
I think this should be in the README:

```
"rubocop": {
      "use_bundle_exec": true,
      "env": {
        "PATH": "~/.asdf/shims:$PATH"
      }
    }
```
