### ISSUE TITLE
Not working with latest sublime text

### ISSUE THREAD

**Issue by bmarvinb** [SublimeLinter/SublimeLinter-rubocop#78]
Hi, I installed the latest sublime text, and want to run rubocop with it, but I have a problem.

I use rvm, ruby is 3.0.2, rubocop installed globally, so it's available from console when I typed 'rubocop', also I have ruby linter, and it works as expected, but rubocop does not work, I don't know why he cannot find any errors. What potentially can go wrong?

My ruby is 3.0.2, rubocop available globally

Path to rubocop is 
```/Users/user/.rvm/rubies/ruby-3.0.2/bin/rubocop```

In my console I got this
```SublimeLinter: WARNING: rubocop cannot locate 'rubocop'```

Ruby linter work well, do you have any suggestion on what can wrong? Thanks for attention

**Comment by bmarvinb** [comment]
When I add this to settings
![image](https://user-images.githubusercontent.com/23120972/139599435-93f95743-e74c-49d5-aa51-ac6b2b2ca675.png)

I have this error
```SublimeLinter: WARNING: rubocop output:
env: ruby_executable_hooks: No such file or directory```

**Comment by bmarvinb** [comment]
Fixed

First
```
# make sure I'm in the global gemset
$ rvm gemset use global
# install the gem
$ gem install rubocop
```

Then

```{
    "linters": {
        "rubocop": {
            "executable": "/Users/Dmytro_Moisieiev/.rvm/gems/ruby-3.0.2@global/wrappers/rubocop"
        }
    }
}```

**Comment by kaste** [comment]
This should probably just work "out-of-the-box" if https://github.com/SublimeLinter/SublimeLinter/issues/1795 gets implemented.
